from django.contrib import admin
from edc_model_admin import audit_fieldset_tuple

from ..admin_site import flourish_child_admin
from ..forms import ChildCBCLForm
from ..models import ChildCBCL
from .model_admin_mixins import ChildCrfModelAdminMixin


@admin.register(ChildCBCL, site=flourish_child_admin)
class ChildCBCLAdmin(ChildCrfModelAdminMixin, admin.ModelAdmin):

    form = ChildCBCLForm

    fieldsets = (
        (None, {
            'fields': [
                'child_visit',
                'report_datetime',
                'acts_young',
                'unapproved_alc_intake',
                'alc_intake_desc',
                'argues_alot',
                'fails_to_finish',
                'enjoys_little',
                'bowel_incontinence',
                'bragging',
                'attention_deficit',
                'obssessive',
                'obssessive_desc',
                'hyperactive',
                'too_dependent',
                'feels_lonely',
                'confused',
                'cries_alot',
                'animal_cruelty',
                'bullies_other',
                'daydreams',
                'self_harms',
                'demands_attention',
                'destroys_belongings',
                'destroys_othr_things',
                'disobedient_home',
                'disobedient_school',
                'eating_problems',
                'unfitting',
                'unremorseful',
                'easily_jealous',
                'breaks_rules',
                'fearful',
                'fearful_desc',
                'fears_school',
                'fear_harmful_thoughts',
                'fear_of_perfection',
                'feels_unloved',
                'feels_paranoia',
                'feels_worthless',
                'accident_prone',
                'fights_involvement',
                'teased_alot',
                'trouble_friends',
                'auditory_hallucination',
                'ah_desc',
                'impulsive',
                'loner',
                'cheating',
                'bites_nails',
                'nervousness',
                'nervous_moments',
                'nervous_desc',
                'nightmares',
                'disliked_by_othrs',
                'constipated',
                'anxiousness',
                'feels_dizzy',
                'feels_guity',
                'overeating',
                'overtired_noreason',
                'overweight', ]}, ),
        ('Physical Problems without known medical cause:', {
            'fields': [
                'body_aches',
                'headaches',
                'nauseous',
                'eye_prob',
                'eye_probl_desc',
                'skin_prob',
                'stomach_aches',
                'vomiting',
                'other_phys_prob',
                'attacks_physical',
                'body_picking',
                'picking_desc',
                'sexparts_public_play',
                'sexparts_play',
                'poor_schoolwork',
                'clumsy',
                'prefers_older_kids',
                'prefers_young_kids',
                'refuses_to_talk',
                'compulsions',
                'compulsions_desc',
                'home_runaway',
                'screams_alot',
                'secretive',
                'sight_hallucinations',
                'sh_desc',
                'self_conscious',
                'sets_fires',
                'sexual_prob',
                'sexual_prob_desc',
                'showing_off',
                'too_shy',
                'sleeps_less',
                'sleeps_more',
                'sleeps_more_desc',
                'inattentive',
                'speech_prob',
                'speech_prob_desc',
                'stares_blankly',
                'steals_at_home',
                'steals_elsewhere',
                'hoarding',
                'hoarding_desc',
                'strange_behavior',
                'behavior_desc',
                'strange_ideas',
                'ideas_desc',
                'irritable',
                'sudden_mood_chng',
                'sulks_alot',
                'suspicious',
                'swearing',
                'self_harm_talks',
                'sleepwalk_talk',
                'sleepwalk_desc',
                'talks_alot',
                'teases_alot',
                'hot_temper',
                'sex_thoughts',
                'threatens_people',
                'thumbsucking',
                'smokes',
                'trouble_sleeping',
                'sleeping_desc',
                'skips_school',
                'underactive',
                'unhappy',
                'unusually_loud',
                'drug_usage',
                'drug_usage_desc',
                'vandalism',
                'daytime_wetting',
                'bedtime_wetting',
                'whining',
                'gender_dissonant',
                'withdrawn',
                'worries',
                'other_problems', ]}, ),
        audit_fieldset_tuple)

    radio_fields = {'acts_young': admin.VERTICAL,
                    'unapproved_alc_intake': admin.VERTICAL,
                    'argues_alot': admin.VERTICAL,
                    'fails_to_finish': admin.VERTICAL,
                    'enjoys_little': admin.VERTICAL,
                    'bowel_incontinence': admin.VERTICAL,
                    'bragging': admin.VERTICAL,
                    'attention_deficit': admin.VERTICAL,
                    'obssessive': admin.VERTICAL,
                    'hyperactive': admin.VERTICAL,
                    'too_dependent': admin.VERTICAL,
                    'feels_lonely': admin.VERTICAL,
                    'confused': admin.VERTICAL,
                    'cries_alot': admin.VERTICAL,
                    'animal_cruelty': admin.VERTICAL,
                    'bullies_other': admin.VERTICAL,
                    'daydreams': admin.VERTICAL,
                    'self_harms': admin.VERTICAL,
                    'demands_attention': admin.VERTICAL,
                    'destroys_belongings': admin.VERTICAL,
                    'destroys_othr_things': admin.VERTICAL,
                    'disobedient_home': admin.VERTICAL,
                    'disobedient_school': admin.VERTICAL,
                    'eating_problems': admin.VERTICAL,
                    'unfitting': admin.VERTICAL,
                    'unremorseful': admin.VERTICAL,
                    'easily_jealous': admin.VERTICAL,
                    'breaks_rules': admin.VERTICAL,
                    'fearful': admin.VERTICAL,
                    'fears_school': admin.VERTICAL,
                    'fear_harmful_thoughts': admin.VERTICAL,
                    'fear_of_perfection': admin.VERTICAL,
                    'feels_unloved': admin.VERTICAL,
                    'feels_paranoia': admin.VERTICAL,
                    'feels_worthless': admin.VERTICAL,
                    'accident_prone': admin.VERTICAL,
                    'fights_involvement': admin.VERTICAL,
                    'teased_alot': admin.VERTICAL,
                    'trouble_friends': admin.VERTICAL,
                    'auditory_hallucination': admin.VERTICAL,
                    'impulsive': admin.VERTICAL,
                    'loner': admin.VERTICAL,
                    'cheating': admin.VERTICAL,
                    'bites_nails': admin.VERTICAL,
                    'nervousness': admin.VERTICAL,
                    'nervous_moments': admin.VERTICAL,
                    'nightmares': admin.VERTICAL,
                    'disliked_by_othrs': admin.VERTICAL,
                    'constipated': admin.VERTICAL,
                    'anxiousness': admin.VERTICAL,
                    'feels_dizzy': admin.VERTICAL,
                    'feels_guity': admin.VERTICAL,
                    'overeating': admin.VERTICAL,
                    'overtired_noreason': admin.VERTICAL,
                    'overweight': admin.VERTICAL,
                    'body_aches': admin.VERTICAL,
                    'headaches': admin.VERTICAL,
                    'nauseous': admin.VERTICAL,
                    'eye_prob': admin.VERTICAL,
                    'skin_prob': admin.VERTICAL,
                    'stomach_aches': admin.VERTICAL,
                    'vomiting': admin.VERTICAL,
                    'attacks_physical': admin.VERTICAL,
                    'body_picking': admin.VERTICAL,
                    'sexparts_public_play': admin.VERTICAL,
                    'sexparts_play': admin.VERTICAL,
                    'poor_schoolwork': admin.VERTICAL,
                    'clumsy': admin.VERTICAL,
                    'prefers_older_kids': admin.VERTICAL,
                    'prefers_young_kids': admin.VERTICAL,
                    'refuses_to_talk': admin.VERTICAL,
                    'compulsions': admin.VERTICAL,
                    'home_runaway': admin.VERTICAL,
                    'screams_alot': admin.VERTICAL,
                    'secretive': admin.VERTICAL,
                    'sight_hallucinations': admin.VERTICAL,
                    'self_conscious': admin.VERTICAL,
                    'sets_fires': admin.VERTICAL,
                    'sexual_prob': admin.VERTICAL,
                    'showing_off': admin.VERTICAL,
                    'too_shy': admin.VERTICAL,
                    'sleeps_less': admin.VERTICAL,
                    'sleeps_more': admin.VERTICAL,
                    'inattentive': admin.VERTICAL,
                    'speech_prob': admin.VERTICAL,
                    'stares_blankly': admin.VERTICAL,
                    'steals_at_home': admin.VERTICAL,
                    'steals_elsewhere': admin.VERTICAL,
                    'hoarding': admin.VERTICAL,
                    'strange_behavior': admin.VERTICAL,
                    'strange_ideas': admin.VERTICAL,
                    'irritable': admin.VERTICAL,
                    'sudden_mood_chng': admin.VERTICAL,
                    'sulks_alot': admin.VERTICAL,
                    'suspicious': admin.VERTICAL,
                    'swearing': admin.VERTICAL,
                    'self_harm_talks': admin.VERTICAL,
                    'sleepwalk_talk': admin.VERTICAL,
                    'talks_alot': admin.VERTICAL,
                    'teases_alot': admin.VERTICAL,
                    'hot_temper': admin.VERTICAL,
                    'sex_thoughts': admin.VERTICAL,
                    'threatens_people': admin.VERTICAL,
                    'thumbsucking': admin.VERTICAL,
                    'smokes': admin.VERTICAL,
                    'trouble_sleeping': admin.VERTICAL,
                    'skips_school': admin.VERTICAL,
                    'underactive': admin.VERTICAL,
                    'unhappy': admin.VERTICAL,
                    'unusually_loud': admin.VERTICAL,
                    'drug_usage': admin.VERTICAL,
                    'vandalism': admin.VERTICAL,
                    'daytime_wetting': admin.VERTICAL,
                    'bedtime_wetting': admin.VERTICAL,
                    'whining': admin.VERTICAL,
                    'gender_dissonant': admin.VERTICAL,
                    'withdrawn': admin.VERTICAL,
                    'worries': admin.VERTICAL, }
