BREASTFEED_ONLY = 'breastfeeding_only'
INFANT = 'infant'
BOTH_BREAST_FEEDING_AND_FORMULA = 'Both breastfeeding and formula feeding'
FORMULA_ONLY = 'Formula feeding only'
PNTA = 'PNTA'  # prefer not to answer'
