from edc_constants.constants import NOT_APPLICABLE, OTHER, NONE

from edc_list_data import PreloadData

list_data = {
    'flourish_child.childdiseases': [
        ('chosp_pneumo', 'Pneumonia'),
        ('chosp_tb', 'Tuberculosis'),
        ('chosp_bronch', 'Bronchiolitis'),
        ('chosp_croup', 'Laryngotracheobronchitis / Croup'),
        ('chosp_diarr', 'Acute diarrheal disease '),
        ('chosp_persisdiarr', 'Persistent diarrheal disease'),
        ('chosp_meningitis', 'Meningitis'),
        ('chosp_malaria', 'Malaria'),
        ('chosp_measle', 'Measles'),
        ('chosp_trauma', 'Trauma'),
        ('chosp_seizure', 'Febrile seizure '),
        ('chosp_malnutrition', 'Malnutrition'),
        ('chosp_anemia', 'Anemia'),
        ('chosp_surgical', 'Surgical reason'),
        ('chosp_other', 'Other'),
    ],
    'flourish_child.chronicconditions': [
        ('chist_asthma', 'Asthma'),
        ('chist_headache', 'Headache (includes migraines, tension headaches)'),
        ('chist_anemia', 'Anemia'),
        ('chist_murmur', 'Cardiac murmur'),
        ('chist_seizure', 'Seizure disorder or other epilepsy'),
        ('chist_diab', 'Diabetes'),
        ('chist_hbp', 'High Blood Pressure'),
        ('chist_cholest', 'High Cholesterol'),
        ('chist_depress', 'Depression'),
        ('chist_lupus', 'Systemic Lupus'),
        ('chist_arthrit ', 'Juvenile rheumatoid arthritis'),
        ('chist_nephrotic ', 'Nephrotic syndrome'),
        ('chist_renal', 'Renal insufficiency'),
        ('chist_nephrol', 'Nephrolithiasis (kidney stones)'),
        ('chist_canc_tumor', 'Cancer (Solid tumor)'),
        ('chist_canc_leuk', 'Cancer (Leukemia, lymphoma related) '),
        ('chist_arrhyt ', 'Cardiac arrhythmia'),
        ('chist_thyroid ', 'Thyroid disorder'),
        ('chist_ibs', 'Inflammatory bowel disease (Crohn’s, ulcerative colitis)'),
        ('chist_other', 'Other, Specify'),
        ('chist_na', 'Not Applicable')
    ],
    'flourish_child.childmedications': [
        (NOT_APPLICABLE, 'Not Applicable'),
        ('cholesterol_meds', 'Cholesterol medications'),
        ('vitamin_d_supp', 'Vitamin D supplement'),
        (NONE, 'None'),
        ('traditional_meds', 'Traditional medications'),
        ('hypertensive_meds', 'Hypertensive medications'),
        ('prenatal_vitamins', 'Prenatal Vitamins')
    ],
    'flourish_child.wcsdxadult': [
        ('wmhist_asympt', 'Asymptomatic'),
        ('wmhist_lymphadeno', 'Persistent generalized lymphadeno'),
        ('wmhist_mod_wloss', 'Unexplained moderate weight loss'),
        ('wmhist_resptract', 'Recurrent resp tract infection'),
        ('wmhist_herpeszost', 'Herpes zoster'),
        ('wmhist_cheilitis', 'Angular cheilitis'),
        ('wmhist_oral_ulcer', 'Recurrent oral ulceration'),
        ('wmhist_papular_pruri', 'Papular pruritic eruptions'),
        ('wmhist_dermatit', 'Seborrhoeic dermatitis'),
        ('wmhist_fungal', 'Fungal nail infections'),
        ('wmhist_sev_wloss', 'Unexplained* severe weight loss'),
        ('wmhist_fev', 'Unexplained persistent fever'),
        ('wmhist_diarr', 'Unexplained chronic diarrhoea'),
        ('wmhist_oral_candid', 'Persistent oral candidiasis'),
        ('wmhist_leukoplakia', 'Oral hairy leukoplakia'),
        ('wmhist_pulm_tb', 'Pulmonary tuberculosis'),
        ('wmhist_bactinfect', 'Severe bacterial infections'),
        ('wmhist_stomatit', 'Stomatitis/gingivitis/periodontis'),
        ('wmhist_anemia', 'Anaemia/neutropaenia/thrombocytopa'),
        ('wmhist_hivwaste', 'HIV wasting syndrome'),
        ('wmhist_pneumonia', 'Pneumocystis pneumonia'),
        ('wmhist_bact_pneumo', 'Recurrent severe bacterial pneumo'),
        ('wmhist_herpesinfec', 'Chronic herpes simplex infection'),
        ('wmhist_oeso_candid', 'Oesophageal candidiasis'),
        ('wmhist_extpulm_tb', 'Extrapulmonary tuberculosis'),
        ('wmhist_kaposi_carc', 'Kaposi\u2019s sarcoma'),
        ('wmhist_cytomeg', 'Cytomegalovirus infection'),
        ('wmhist_cns', 'CNS toxoplasmosis'),
        ('wmhist_hivenceph', 'HIV encephalopathy'),
        ('wmhist_meningitis', 'Exp cryptococcosis/meningitis'),
        ('wmhist_dissnon_tb', 'Diss non-TB mycobacterial infection'),
        ('wmhist_leukoence', 'Prog multifocal leukoencephalopathy'),
        ('wmhist_crypto', 'Chronic cryptosporidiosis'),
        ('wmhist_isospor', 'Chronic isosporiasis'),
        ('wmhist_mycosis', 'Disseminated mycosis'),
        ('wmhist_septica', 'Recurrent septicaemia'),
        ('wmhist_lymphoma', 'Lymphoma'),
        ('wmhist_cerv_carc', 'Invasive cervical carcinoma'),
        ('wmhist_leishman', 'Atypical disseminated leishmaniasis'),
        ('wmhist_cardiomy', 'Sympt nephropathy/cardiomyopathy'),
        ('wmhist_na', 'Not Applicable'),
    ],
    'flourish_child.childcovidsymptoms': [
        ('c19c_iso_chestpain', 'Chest pain'),
        ('c19c_iso_chills', 'Chills'),
        ('c19c_iso_cough', 'Cough'),
        ('c19c_iso_diarr ', 'Diarrhea '),
        ('c19c_iso_fev', 'Fever > 37.5 Degree Celsius'),
        ('c19c_iso_aches', 'Muscle aches'),
        ('c19c_iso_nasal', 'Nasal Congestion/Runny Nose'),
        ('c19c_iso_nausea  ', 'Nausea/vomiting'),
        ('c19c_iso_sob', 'Shortness of breath'),
        ('c19c_iso_throat', 'Sore throat'),
        ('c19c_iso_headache', 'Headache'),
        ('c19c_iso_losssmell', 'Loss of Smell'),
        ('c19c_iso_losstaste', 'Loss of Taste'),
        ('c19c_iso_nosympt', 'No Symptoms'),
    ],
    'flourish_child.childcovidsymptomsafter14days': [
        ('c19c_14d_chestpain', 'Chest pain'),
        ('c19c_14d_chills', 'Chills'),
        ('c19c_14d_cough', 'Cough'),
        ('c19c_14d_diarr ', 'Diarrhea '),
        ('c19c_14d_fev', 'Fever > 37.5 Degree Celsius'),
        ('c19c_14d_aches', 'Muscle aches'),
        ('c19c_14d_nasal', 'Nasal Congestion'),
        ('c19c_14d_nausea  ', 'Nausea/vomiting'),
        ('c19c_14d_sob', 'Shortness of breath'),
        ('c19c_14d_throat', 'Sore throat'),
        ('c19c_14d_headache', 'Headache'),
        ('c19c_14d_losssmell', 'Loss of Smell'),
        ('c19c_14d_losstaste', 'Loss of Taste'),
        ('c19c_14d_nosympt', 'No Symptoms'),
    ],
    'flourish_child.solidfoods': [
        ('food_grains', 'Grains, roots and tubers'),
        ('food_legume', 'Legumes and nuts'),
        ('food_dairy', 'Dairy products (milk, yogurt, cheese)'),
        ('food_flesh', 'Flesh foods (meat, fish, poultry and liver/organ meat)'),
        ('food_eggs', 'Eggs'),
        ('food_porridge', 'Porridge'),
        ('food_vita',
         'Vitamin A rich fruits and vegetables (carrots, pumpkin, sweet potato)'),
        ('food_fruitsvege', 'Other fruits and vegetables'),
        ('food_othersolid', 'Other solid foods'),
    ],
}

preload_data = PreloadData(
    list_data=list_data)
